/*
 * form — C ABI over form-core.
 *
 * GENERATED by cbindgen from core/crates/form-ffi. Do not edit by hand: run `make headers`
 * and commit the result. `cargo test -p form-ffi` fails if this file has drifted.
 *
 * Contract (docs/specs/00-protocol.md):
 *   - Every payload is UTF-8 JSON. Nothing else crosses this boundary.
 *   - Strings returned by form_core_query / form_core_dispatch are owned by the caller and
 *     must be released with form_string_free.
 *   - Events are delivered on one dedicated thread, in order, never concurrently. The
 *     callback must not re-enter the core.
 */

#ifndef FORM_H
#define FORM_H

#include <stdint.h>
#include <stddef.h>

/*
 Bumped on any breaking protocol change. The client asserts a match at startup.
 */
#define FORM_ABI_VERSION 1

typedef struct FormCoreHandle FormCoreHandle;

/*
 Receives one serialized `form_core::Event` per call. `json` is valid only for the
 duration of the call — copy it.
 */
typedef void (*FormEventCallback)(const char *json, size_t len, void *ctx);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 The ABI version this library was built against. Swift refuses to run on a mismatch.
 */
uint32_t form_abi_version(void);

/*
 Create a core. Returns NULL on failure; `form_last_error()` explains why.

 # Safety
 `config_json` must be a valid NUL-terminated UTF-8 string.
 */
FormCoreHandle *form_core_new(const char *config_json);

/*
 Free a core. Safe to call while a run is streaming.

 # Safety
 `ptr` must come from `form_core_new` and must not be used afterwards.
 */
void form_core_free(FormCoreHandle *ptr);

/*
 Register an event callback. Returns a positive token, or -1 on failure.

 # Safety
 `ptr` must be a live handle from `form_core_new`.
 */
int32_t form_core_subscribe(FormCoreHandle *ptr, FormEventCallback callback, void *ctx);

/*
 After this returns, the callback is guaranteed not to be invoked again.

 # Safety
 `ptr` must be a live handle from `form_core_new`.
 */
void form_core_unsubscribe(FormCoreHandle *ptr, int32_t token);

/*
 Synchronous read. Never returns NULL; failures come back as an error envelope.

 # Safety
 `ptr` must be a live handle; `query_json` a valid NUL-terminated UTF-8 string.
 The returned string must be freed with `form_string_free`.
 */
char *form_core_query(FormCoreHandle *ptr, const char *query_json);

/*
 Asynchronous command. Returns an ack envelope; outcomes arrive as events.

 # Safety
 `ptr` must be a live handle; `command_json` a valid NUL-terminated UTF-8 string.
 The returned string must be freed with `form_string_free`.
 */
char *form_core_dispatch(FormCoreHandle *ptr, const char *command_json);

/*
 Release a string returned by `form_core_query` or `form_core_dispatch`.

 # Safety
 `s` must have come from this library and must not be used afterwards.
 */
void form_string_free(char *s);

/*
 Last error on the *calling thread*, valid until the next failing call on that thread.
 */
const char *form_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FORM_H */
